- Word Guess.py
Created a Word Guess Game in Python.
Do comment if any problem.
> Create Word Guess.py

- tic_tac_toe.py
A tic_tac_toe game using python and tkinter module has beed added.
> tic-tac-toe game added

- pdf_reader.py
Made a pdf reader using python . please merge it as soon as possible.
>  pdf_reader.py

- SentimentAnalysis.py
SENTIMENT ANALYSIS USING NLTK LIBRARY TO READ PDFS AND POEMS ETC
> sentimentanalysis.py

- Dice.py
> hacktoberfest2022

- Speed Typing Test Project
In this Python project, we have written a python code to create an amazing project that will allow us to test and improve our typing speed.
Also please add a **hacktoberfest accepted** tag after merged.
Thank you for the opportunity.
> Speed Typing Test Project

- pattern.py
I added the pattern of pyton Using List .
> added pattern

- Text_to_Speech_PythonProject.py
A text to speech generator code written in python by me.
Also please add an **Hacktoberfest accepted** tag after merged.
Thank you for the opportunity.
>  Text_to_Speech_PythonProject.py

- bounce_ball.py
Bounce ball game using tkniter module is added.
> bounce_ball.py is added.

- diabetes-predictor.ipynb
Data Science project that predicts diabetes and compares several ML algos in imnplementation.
> diabetes predictor

- get_wifi_password.py
This is a simple python script that tells you the password of the wifi you're connected with. Please merge this PR.
> get_wifi_password.py

- Steganography.py
> steganography

- Tic-tac-toe.py
> Tic-tac-toe

- Guess-the-number-game.py
- hand-detection.py
Python code for hand tracking, written using mediapipe library by google.
> Hand track

- 3. Longest Substring Without Repeating Characters.py
Given a string s, find the length of the longest substring without repeating characters.
Example 1:
Input: s = "abcabcbb"
Output: 3
Explanation: The answer is "abc", with the length of 3.
Example 2:
Input: s = "bbbbb"
Output: 1
Explanation: The answer is "b", with the length of 1.
Example 3:
Input: s = "pwwkew"
Output: 3
Explanation: The answer is "wke", with the length of 3. Notice that the answer must be a substring, "pwke" is a subsequence and not a substring.
> 3. Longest Substring Without Repeating Characters.py

- spam-ham_predictor.py
> Spam messages classifier

- khushi
> linked list added

- Money Control Scrapper/moneycontrol_scrapper.py
Created Money Control Scrapper
> Created Money Control Scrapper

- pallindromeinLL.py
@Arunim313  Please merge this pull request.
> Palindrome Linked List in Python

- face detection project/intersectionofLL.py
Please merge the pull request @Arunim313.
> Intersection of Linked Lists in python

- face detection project/notetaking.py
- guessgame.py
I use various systems to store such information, like Todoist, Evernote, email, etc.
As I was working on my computer and an idea or task came into my mind, I had to open the relevant software and compose a note there, which was super counterproductive.
Since this tool is created, I can simply go to my terminal and send my thoughts to either of these systems with one command.
> A notetaking tool

- wifi_password_show.py
> wifi_password_using_python

- Contacts.py
Thanks for reading my pull request!!
> Contacts.py

- main.py
Calculate bias and Variance by mean and variance of data in normal distribution.
> Find bias and vriance.

- Speed Typing test.py
- rock paper scissors.py
Speed typing test window developed using python to check the typing speed
kindly merge my PR in order to contribute to this repo
> Speed typing test using Python

- download_and_unzip.py
This particular script is capable of downloading and unzipping files in a particular directory given the file url.
> Python script to download and unzip a file given the url

- Website Blocker Python project
A fully working website blocker python project implemented code.
Also please add a **hacktoberfest accepted** label after merged.
Thank you for the opportunity.
> Website Blocker Python project

- Hand-tracking Module/handTrackMin.py
- Hand-tracking Module/handTrackingModule.py
- Import this module to any existing project.
- Made using python mediapipe library.
> added hand tracking module

- number_recognition.ipynb
It is a deep learning model for handwritten digit recognition.
> added number recognition model
